### ISSUE TITLE
Test-kitchen suite references unknown cookbook

### ISSUE THREAD

**Issue by martinb3** [opscode-cookbooks/firewall#30]
Hello! It seems .kitchen.ymn references a `firewall-test` cookbook:

```yaml
suites:
- name: default
  run_list:
  - recipe[firewall::default]
  - recipe[firewall-test::default]
```

Is that the same as the cookbook named `fake` in the test fixtures? Or is that some cookbook from elsewhere? I don't see an entry in Berksfile for it, so I'm assuming `firewall-test` should really be `fake`?
